url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Bitcoin Cash Academy" # the name of your site, e.g. ACME Corp.

# permalink: /:title/

collections:
    articles:
        output: true
    tutorials:
        output: true

defaults:
    - scope:
          path: "_articles/en"
          type: "articles"
      values:
          permalink: "en/:title/"
          language: en
    - scope:
          path: "_tutorials/en"
          type: "tutorials"
      values:
          permalink: "en/:title/"
          language: en
    - scope:
          path: "_articles/es"
          type: "articles"
      values:
          permalink: "es/:title/"
          language: es
    - scope:
          path: "_tutorials/es"
          type: "tutorials"
      values:
          permalink: "es/:title/"
          language: es
